version: '2.1'
services:
    rabbit: # rabbitMQ 消息队列
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass # Password!
        ports:
            - "5672:5672"

    judger: # 执行用户程序的评测容器
        build:
            context: ./judger/
            dockerfile: Dockerfile
        links:
            - rabbit
        depends_on:
            - rabbit
        pids_limit: 16

    web: # 网页端，给 worker 发任务
        build:
            context: ./web/
            dockerfile: Dockerfile
        links:
            - rabbit
            - judger
        depends_on:
            - rabbit
            - judger
        ports:
            - "5001:5001"
             
