version: '2.1'
services:
    rabbit: # rabbitMQ 消息队列
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass # Password!
        ports:
            - "5672:5672"

    worker: # 执行用户程序的评测容器
        build:
            context: .
            dockerfile: dockerfile_worker
        volumes:
            - .:/judgeApp
        links:
            - rabbit
        depends_on:
            - rabbit
        pids_limit: 16

    manager: # 处理评测结果 & 给 worker 发任务
        build:
            context: .
            dockerfile: dockerfile_manager
        volumes:
            - .:/judgeApp
        links:
            - rabbit
            - worker
        depends_on:
            - rabbit
            - worker
             
