sudo: true
dist: trusty
language: python
python:
  - 3.5
addons:
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y seccomp libseccomp-dev libcap-dev libcap2
script:
  - make
  - python3 main.py
before_cache:
  - true
cache:
  directories:
    - $HOME/virtualenv/python3.*
