sudo: true
dist: trusty
language: python
python:
  - 3.5
addons:
before_install:
  - python3 setup.py enable-java enable-pascal
install:
  - sudo ./install.sh
script:
  - make
  - python3 main.py
  - python3 main.py cleanup
before_cache:
  - true
cache:
  directories:
    - $HOME/virtualenv/python3.5.*
