sudo: true
dist: trusty
language: python
python:
  - 3.5
addons:
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qqy seccomp libseccomp-dev libcap-dev fp-compiler
  - sudo ${PWD}/.ci/envfix.sh
script:
  - make
  - python3 main.py
  - python3 main.py cleanup
before_cache:
  - true
cache:
  directories:
    - $HOME/virtualenv/python3.5.*
